apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- influx-auth.secret.yaml
- release.yaml
configMapGenerator:
- name: influx-values
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml
