apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hass-influxdb
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: influxdb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "< 6.0"
  install:
    disableWaitForJobs: true
  upgrade:
    preserveValues: false # ensure only the values set here are used
  valuesFrom:
  - kind: ConfigMap
    name: influx-values
