apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-configuration
data:
  configuration.yaml: |-
      homeassistant:
        external_url: https://hass.<domain>
        internal_url: http://192.168.0.110:8123
        time_zone: Europe/Vienna
        customize: !include customize.yaml
        packages: !include_dir_named packages

      # Loads default set of integrations. Do not remove.
      default_config:

      # http config
      http:
        use_x_forwarded_for: true
        ip_ban_enabled: false
        # k8s pod network & home network
        trusted_proxies:
          - 10.0.0.0/8
          - 192.168.0.0/16

      # Load frontend themes from the themes folder
      frontend:
        themes: !include_dir_merge_named themes
