apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
- _ns.yaml
# - addons
- code-sudo.secret.yaml
- hass-configuration.yaml
- hass-secrets.secret.yaml
- release.yaml
configMapGenerator:
- name: hass-values
  files:
  - values.yaml
configurations:
- kustomizeconfig.yaml
