apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: '>= 2.4.0'
  install:
    disableWaitForJobs: true
  upgrade:
    preserveValues: false # ensure only the values set here are used
  valuesFrom:
  - kind: ConfigMap
    name: hass-values
