apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  interval: 5m0s
  path: ./home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    # Use the sops provider
    provider: sops
    secretRef:
      name: sops-age
